version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: doctrine/doctrine-migrations-bundle
    versions:
    - 3.0.2
    - 3.1.0
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.69
    - 0.12.71
    - 0.12.73
    - 0.12.74
    - 0.12.75
    - 0.12.76
    - 0.12.77
    - 0.12.78
    - 0.12.81
    - 0.12.82
    - 0.12.83
  - dependency-name: symfony/translation
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/validator
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/http-client
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/templating
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/browser-kit
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: knpuniversity/oauth2-client-bundle
    versions:
    - 2.7.0
  - dependency-name: league/oauth2-google
    versions:
    - 3.0.3
