doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                LEAST: DoctrineExtensions\Query\Mysql\Least
                GREATEST: DoctrineExtensions\Query\Mysql\Greatest
                LPAD: DoctrineExtensions\Query\Mysql\Lpad
                REPLACE: DoctrineExtensions\Query\Mysql\Replace
                RPAD: DoctrineExtensions\Query\Mysql\Rpad
                SUBSTRING_INDEX: DoctrineExtensions\Query\Mysql\SubstringIndex
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                UNIX_TIMESTAMP: DoctrineExtensions\Query\Mysql\UnixTimestamp
                ROUND: DoctrineExtensions\Query\Mysql\Round
                NOW: DoctrineExtensions\Query\Mysql\Now
