twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        SITE_TITLE: '%env(SITE_TITLE)%'
        TCP_API_PORT: '%env(TCP_API_PORT)%'
    exception_controller: null
