version: '3'
services:
  db:
    image: mariadb
    environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASS}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASS}
    volumes:
        - ./database:/var/lib/mysql
    ports:
        - 3306:3306
  php-apache:
    build:
      context: ./
      dockerfile: Dockerfile.php-apache
    env_file:
        - .env
    environment:
        - ServerName=localhost
    volumes:
        - .:/var/www
        - ./public:/var/www/html
        - ./var/log/app.log:/var/log/app.log
    links:
        - db
    ports:
        - 80:80
        - 3000:80
        - 61080:61080
